UPDATE Civilizations
SET Name = 'LOC_CIVILIZATION_ARMAGH_TEST_NAME', Description = 'LOC_CIVILIZATION_ARMAGH_TEST_DESC', Adjective = 'LOC_CIVILIZATION_ARMAGH_TEST_ADJ'
WHERE CivilizationType = 'CIVILIZATION_ARMAGH';

UPDATE Leaders
SET Name = 'LOC_CIVILIZATION_ARMAGH_TEST_NAME'
WHERE LeaderType = 'LEADER_MINOR_CIV_ARMAGH';