

INSERT INTO	Types
		(Type,												Kind			)
VALUES	('TRAIT_CIVILIZATION_SORTIENT_LINENOPOLIS',		'KIND_TRAIT'	);

INSERT INTO	CivilizationTraits
		(CivilizationType,						TraitType									)
VALUES	('CIVILIZATION_SORTIENT_ULSTER',		'TRAIT_CIVILIZATION_SORTIENT_LINENOPOLIS'	);

INSERT INTO	Traits	
		(TraitType,											Name,														Description														)
VALUES	('TRAIT_CIVILIZATION_SORTIENT_LINENOPOLIS',		'LOC_TRAIT_CIVILIZATION_SORTIENT_LINENOPOLIS_NAME',		'LOC_TRAIT_CIVILIZATION_SORTIENT_LINENOPOLIS_DESCRIPTION'	);


INSERT INTO RequirementSets(RequirementSetId, RequirementSetType)
VALUES('PLOT_HAS_LUXURY_SET', 'REQUIREMENTSET_TEST_ALL');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId)
VALUES('PLOT_HAS_LUXURY_SET', 'REQUIRES_PLOT_HAS_LUXURY');

INSERT INTO	Modifiers
		(ModifierId,																	ModifierType 					)
VALUES	('MODIFIER_SORTIENT_LINENOPOLIS_INCREASED_INDUSTRIAL_BUILD',		'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PRODUCTION');

INSERT INTO	Modifiers
		(ModifierId,																	ModifierType, SubjectRequirementSetId 					)
VALUES	('MODIFIER_LUXURY_PRODUCTION', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'PLOT_HAS_LUXURY_SET');


INSERT INTO	TraitModifiers	
		(TraitType,											ModifierId									)
VALUES 	('TRAIT_CIVILIZATION_SORTIENT_LINENOPOLIS', 'GREATPERSON_CULTURE_BOMB_TRIGGER_INDUSTRIAL_ZONE'),
		('TRAIT_CIVILIZATION_SORTIENT_LINENOPOLIS', 'MODIFIER_LUXURY_PRODUCTION');	

INSERT INTO	ModifierArguments (ModifierId, Name, Value)
VALUES	('MODIFIER_SORTIENT_LINENOPOLIS_INCREASED_INDUSTRIAL_BUILD', 'DistrictType', 'DISTRICT_INDUSTRIAL_ZONE'),
		('MODIFIER_SORTIENT_LINENOPOLIS_INCREASED_INDUSTRIAL_BUILD', 'Amount', 20),
		('MODIFIER_LUXURY_PRODUCTION', 'YieldType', 'YIELD_PRODUCTION'),
		('MODIFIER_LUXURY_PRODUCTION', 'Amount', '3');
