INSERT INTO Types	
		(Type,													Kind						)
VALUES	('TRAIT_CIVILIZATION_BUILDING_ULSTER_LINEN_MILL',		'KIND_TRAIT'				),
		('BUILDING_ULSTER_LINEN_MILL',							'KIND_BUILDING'			);
		
INSERT INTO CivilizationTraits
		(TraitType,												CivilizationType			)
VALUES	('TRAIT_CIVILIZATION_BUILDING_ULSTER_LINEN_MILL',	'CIVILIZATION_SORTIENT_ULSTER'		);


INSERT INTO Traits
		(TraitType,												Name,											Description											)
VALUES	('TRAIT_CIVILIZATION_BUILDING_ULSTER_LINEN_MILL',		'LOC_BUILDING_ULSTER_LINEN_MILL_NAME',		'LOC_BUILDING_ULSTER_LINEN_MILL_DESCRIPTION'		);

INSERT INTO Modifiers 
		(ModifierId, ModifierType)
VALUES 	('TRAIT_SORTIENT_GOLD_LUXURY_RESOURCES_INTERNATIONAL', 'MODIFIER_PLAYER_CITIES_TRADE_ROUTE_YIELD_PER_LOCAL_LUXURY_RESOURCE_FOR_INTERNATIONAL'),
		('TRAIT_SORTIENT_PRODUCTION_LUXURY_RESOURCES_INTERNATIONAL', 'MODIFIER_PLAYER_CITIES_TRADE_ROUTE_YIELD_PER_LOCAL_LUXURY_RESOURCE_FOR_INTERNATIONAL');

INSERT INTO ModifierArguments
		(ModifierId, Name, Type, Value)
VALUES 	('TRAIT_SORTIENT_GOLD_LUXURY_RESOURCES_INTERNATIONAL', 'YieldType', 'ARGTYPE_IDENTITY', 'YIELD_GOLD'),
		('TRAIT_SORTIENT_GOLD_LUXURY_RESOURCES_INTERNATIONAL', 'Amount', 'ARGTYPE_IDENTITY', 4),
		('TRAIT_SORTIENT_PRODUCTION_LUXURY_RESOURCES_INTERNATIONAL', 'YieldType', 'ARGTYPE_IDENTITY', 'YIELD_PRODUCTION'),
		('TRAIT_SORTIENT_PRODUCTION_LUXURY_RESOURCES_INTERNATIONAL', 'Amount', 'ARGTYPE_IDENTITY', 2);

INSERT INTO Buildings
	(
		BuildingType,
		Name,
		Description,
		TraitType,
		PrereqDistrict,
		PrereqTech,
		PurchaseYield,
		Cost,
		Maintenance,
		Housing,
		CitizenSlots,
		RegionalRange,
		AdvisorType
	)
VALUES(
		'BUILDING_ULSTER_LINEN_MILL',
		'LOC_BUILDING_ULSTER_LINEN_MILL_NAME',
		'LOC_BUILDING_ULSTER_LINEN_MILL_DESCRIPTION',
		'TRAIT_CIVILIZATION_BUILDING_ULSTER_LINEN_MILL',
		'DISTRICT_INDUSTRIAL_ZONE',
		'TECH_INDUSTRIALIZATION',
		'YIELD_GOLD',
		312,
		2,
		2,
		2,
		6,
		'ADVISOR_GENERIC'
);

INSERT INTO BuildingReplaces
			(CivUniqueBuildingType,					ReplacesBuildingType)
VALUES		('BUILDING_ULSTER_LINEN_MILL',			'BUILDING_FACTORY');

INSERT INTO BuildingPrereqs (Building, PrereqBuilding)
VALUES	('BUILDING_ULSTER_LINEN_MILL', 'BUILDING_WORKSHOP'),
		('BUILDING_POWER_PLANT', 'BUILDING_ULSTER_LINEN_MILL');

INSERT INTO Building_GreatPersonPoints (BuildingType, GreatPersonClassType, PointsPerTurn)
VALUES	('BUILDING_ULSTER_LINEN_MILL', 'GREAT_PERSON_CLASS_ENGINEER', 1);

INSERT INTO Building_YieldChanges (BuildingType, YieldType, YieldChange)
VALUES	('BUILDING_ULSTER_LINEN_MILL', 'YIELD_PRODUCTION', 4);

INSERT INTO BuildingModifiers (BuildingType, ModifierId)
VALUES	('BUILDING_ULSTER_LINEN_MILL', 'TRAIT_SORTIENT_GOLD_LUXURY_RESOURCES_INTERNATIONAL'),
		('BUILDING_ULSTER_LINEN_MILL', 'TRAIT_SORTIENT_PRODUCTION_LUXURY_RESOURCES_INTERNATIONAL');
