-- Civilization_ModSupport
-- Author: osort
-- DateCreated: 6/21/2021 9:19:56 AM
--------------------------------------------------------------

INSERT INTO LocalizedText (Language, Tag, Text)
VALUES
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_JFD_NOMADS_CIVILIZATION_SORTIENT_ULSTER',  'Ultaigh Tribes'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_JFD_NOMADS_CIVILIZATION_SORTIENT_ULSTER',  'Ultaigh Tribes'	),

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_CHIEFDOM_LARGE_CIVILIZATION_SORTIENT_ULSTER',  '{1_Name}, R� Ulad'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_CHIEFDOM_LARGE_CIVILIZATION_SORTIENT_ULSTER',  'High Chieftess {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_CHIEFDOM_LARGE_CIVILIZATION_SORTIENT_ULSTER',  'Ulaid High Chiefdom'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_CHIEFDOM_LARGE_CIVILIZATION_SORTIENT_ULSTER',  'Ulaid High Chiefdom'	),

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_CHIEFDOM_SMALL_CIVILIZATION_SORTIENT_ULSTER',  '{1_Name}, R� Ulad'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_CHIEFDOM_SMALL_CIVILIZATION_SORTIENT_ULSTER',  'Chieftess {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_CHIEFDOM_SMALL_CIVILIZATION_SORTIENT_ULSTER',  'Ulaid Chiefdom'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_CHIEFDOM_SMALL_CIVILIZATION_SORTIENT_ULSTER',  'Ulaid Chiefdom'	),

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_AUTOCRACY_CIVILIZATION_SORTIENT_ULSTER',  'Emperor Hume I'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_AUTOCRACY_CIVILIZATION_SORTIENT_ULSTER',  'Empress {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_AUTOCRACY_CIVILIZATION_SORTIENT_ULSTER',  'Ulaid Empire'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_AUTOCRACY_CIVILIZATION_SORTIENT_ULSTER',  'Ulaid Empire'	),

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_CLASSICAL_REPUBLIC_CIVILIZATION_SORTIENT_ULSTER',  'Consul {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_CLASSICAL_REPUBLIC_CIVILIZATION_SORTIENT_ULSTER',  'Consul {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_CLASSICAL_REPUBLIC_CIVILIZATION_SORTIENT_ULSTER',  'Republic of Ulaid'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_CLASSICAL_REPUBLIC_CIVILIZATION_SORTIENT_ULSTER',  'Republic of Ulaid'	),

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_OLIGARCHY_CIVILIZATION_SORTIENT_ULSTER',  'Chairman {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_OLIGARCHY_CIVILIZATION_SORTIENT_ULSTER',  'Senatrix {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_OLIGARCHY_CIVILIZATION_SORTIENT_ULSTER',  'Council of Stormont'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_OLIGARCHY_CIVILIZATION_SORTIENT_ULSTER',  'Council of Stormont'	),

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_JFD_HORDE_CIVILIZATION_SORTIENT_ULSTER',  'Chieftain {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_JFD_HORDE_CIVILIZATION_SORTIENT_ULSTER',  'Chieftainess {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_JFD_HORDE_CIVILIZATION_SORTIENT_ULSTER',  '{1_Adjective} Horde'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_JFD_HORDE_CIVILIZATION_SORTIENT_ULSTER',  '{1_Adjective} Horde'	),

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_EMPIRE_CIVILIZATION_SORTIENT_ULSTER',  'Emperor {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_EMPIRE_CIVILIZATION_SORTIENT_ULSTER',  'Empress {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_EMPIRE_CIVILIZATION_SORTIENT_ULSTER',  'Ulster Empire'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_EMPIRE_CIVILIZATION_SORTIENT_ULSTER',  'Ulster Empire'	),

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_JFD_NOMADS_CIVILIZATION_SORTIENT_ULSTER',  'Elder {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_JFD_NOMADS_CIVILIZATION_SORTIENT_ULSTER',  'Matriarch {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_JFD_NOMADS_CIVILIZATION_SORTIENT_ULSTER',  '{1_Adjective} Tribes'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_JFD_NOMADS_CIVILIZATION_SORTIENT_ULSTER',  '{1_Adjective} Tribes'	),

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_JFD_NOBLE_REPUBLIC_CIVILIZATION_SORTIENT_ULSTER',  'Prince {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_JFD_NOBLE_REPUBLIC_CIVILIZATION_SORTIENT_ULSTER',  'Princess {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_JFD_NOBLE_REPUBLIC_CIVILIZATION_SORTIENT_ULSTER',  '{1_Adjective} Commonwealth'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_JFD_NOBLE_REPUBLIC_CIVILIZATION_SORTIENT_ULSTER',  '{1_Adjective} Commonwealth'	),

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_JFD_ABSOLUTE_MONARCHY_CIVILIZATION_SORTIENT_ULSTER',  'Emperor {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_JFD_ABSOLUTE_MONARCHY_CIVILIZATION_SORTIENT_ULSTER',  'Empress {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_JFD_ABSOLUTE_MONARCHY_CIVILIZATION_SORTIENT_ULSTER',  '{1_Adjective} Empire'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_JFD_ABSOLUTE_MONARCHY_CIVILIZATION_SORTIENT_ULSTER',  '{1_Adjective} Empire'	),

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_SYNTHETIC_TECHNOCRACY_CIVILIZATION_SORTIENT_ULSTER',  'Technocrat {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_SYNTHETIC_TECHNOCRACY_CIVILIZATION_SORTIENT_ULSTER',  'Technocrat {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_SYNTHETIC_TECHNOCRACY_CIVILIZATION_SORTIENT_ULSTER',  'Ulster Technate'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_SYNTHETIC_TECHNOCRACY_CIVILIZATION_SORTIENT_ULSTER',  'Ulster Technate'	),

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_JFD_PARLIAMENTARY_DEMOCRACY_CIVILIZATION_SORTIENT_ULSTER',  'Prime Minister {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_JFD_PARLIAMENTARY_DEMOCRACY_CIVILIZATION_SORTIENT_ULSTER',  'Prime Minister {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_JFD_PARLIAMENTARY_DEMOCRACY_CIVILIZATION_SORTIENT_ULSTER',  '{1_Adjective} Republic'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_JFD_PARLIAMENTARY_DEMOCRACY_CIVILIZATION_SORTIENT_ULSTER',  '{1_Adjective} Republic'	),

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_JFD_POLIS_CIVILIZATION_SORTIENT_ULSTER',  'Tyrant {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_JFD_POLIS_CIVILIZATION_SORTIENT_ULSTER',  'Tyrant {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_JFD_POLIS_CIVILIZATION_SORTIENT_ULSTER',  '{1_Capital}'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_JFD_POLIS_CIVILIZATION_SORTIENT_ULSTER',  '{1_Capital}'	),

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_MERCHANT_REPUBLIC_TINY_CIVILIZATION_SORTIENT_ULSTER',  'Mayor {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_MERCHANT_REPUBLIC_TINY_CIVILIZATION_SORTIENT_ULSTER',  'Mayor {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_MERCHANT_REPUBLIC_TINY_CIVILIZATION_SORTIENT_ULSTER',  '{1_Capital}'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_MERCHANT_REPUBLIC_TINY_CIVILIZATION_SORTIENT_ULSTER',  '{1_Capital}'	),
	
	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_MONARCHY_TINY_CIVILIZATION_SORTIENT_ULSTER',  'Lord {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_MONARCHY_TINY_CIVILIZATION_SORTIENT_ULSTER',  'Lady {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_MONARCHY_TINY_CIVILIZATION_SORTIENT_ULSTER',  '{1_Capital} Lordship'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_MONARCHY_TINY_CIVILIZATION_SORTIENT_ULSTER',  '{1_Capital} Lordship'	),

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_MONARCHY_SMALL_CIVILIZATION_SORTIENT_ULSTER',  '{1_Name}, Earl of Ulster'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_MONARCHY_SMALL_CIVILIZATION_SORTIENT_ULSTER',  'Countess {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_MONARCHY_SMALL_CIVILIZATION_SORTIENT_ULSTER',  'Earldom of Ulster'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_MONARCHY_SMALL_CIVILIZATION_SORTIENT_ULSTER',  'Earldom of Ulster'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_MONARCHY_SMALL_ADJ_CIVILIZATION_SORTIENT_ULSTER',  'Ulster Earldom'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_MONARCHY_SMALL_ADJ_CIVILIZATION_SORTIENT_ULSTER',  'Ulster Earldom'	),

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_MONARCHY_MEDIUM_CIVILIZATION_SORTIENT_ULSTER',  'King {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_MONARCHY_MEDIUM_CIVILIZATION_SORTIENT_ULSTER',  'Queen {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_MONARCHY_MEDIUM_CIVILIZATION_SORTIENT_ULSTER',  'Kingdom of Ulster'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_MONARCHY_MEDIUM_CIVILIZATION_SORTIENT_ULSTER',  'Kingdom of Ulster'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_MONARCHY_MEDIUM_ADJ_CIVILIZATION_SORTIENT_ULSTER',  'Ulster Kingdom'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_MONARCHY_MEDIUM_ADJ_CIVILIZATION_SORTIENT_ULSTER',  'Ulster Kingdom'	),

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_MONARCHY_LARGE_CIVILIZATION_SORTIENT_ULSTER',  'High King John I'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_MONARCHY_LARGE_CIVILIZATION_SORTIENT_ULSTER',  'High Queen {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_MONARCHY_LARGE_CIVILIZATION_SORTIENT_ULSTER',  'High Kingdom of Ulster'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_MONARCHY_LARGE_CIVILIZATION_SORTIENT_ULSTER',  'High Kingdom of Ulster'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_MONARCHY_LARGE_ADJ_CIVILIZATION_SORTIENT_ULSTER',  'Ulster High Kingdom'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_MONARCHY_LARGE_ADJ_CIVILIZATION_SORTIENT_ULSTER',  'Ulster High Kingdom'	),

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_MERCHANT_REPUBLIC_LARGE_SEA_CIVILIZATION_SORTIENT_ULSTER',  'His Serenity, Doge {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_MERCHANT_REPUBLIC_LARGE_SEA_CIVILIZATION_SORTIENT_ULSTER',  'Her Serenity, Dogaressa {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_MERCHANT_REPUBLIC_LARGE_SEA_CIVILIZATION_SORTIENT_ULSTER',  'Most Serene Republic of Ulster'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_MERCHANT_REPUBLIC_LARGE_SEA_CIVILIZATION_SORTIENT_ULSTER',  'Most Serene Republic of Ulster'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_MERCHANT_REPUBLIC_LARGE_SEA_ADJ_CIVILIZATION_SORTIENT_ULSTER',  'Most Serene Ulster Republic'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_MERCHANT_REPUBLIC_LARGE_SEA_ADJ_CIVILIZATION_SORTIENT_ULSTER',  'Most Serene Ulster Republic'	),

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_MERCHANT_REPUBLIC_MEDIUM_SEA_CIVILIZATION_SORTIENT_ULSTER',  'Serene Prince {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_MERCHANT_REPUBLIC_MEDIUM_SEA_CIVILIZATION_SORTIENT_ULSTER',  'Serene Princess {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_MERCHANT_REPUBLIC_MEDIUM_SEA_CIVILIZATION_SORTIENT_ULSTER',  'Serene Republic of Ulster'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_MERCHANT_REPUBLIC_MEDIUM_SEA_CIVILIZATION_SORTIENT_ULSTER',  'Serene Republic of {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_MERCHANT_REPUBLIC_MEDIUM_SEA_ADJ_CIVILIZATION_SORTIENT_ULSTER',  'Serene Ulster Republic'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_MERCHANT_REPUBLIC_MEDIUM_SEA_ADJ_CIVILIZATION_SORTIENT_ULSTER',  'Serene Ulster Republic'	),

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_MERCHANT_REPUBLIC_SMALL_SEA_CIVILIZATION_SORTIENT_ULSTER',  'Doge {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_MERCHANT_REPUBLIC_SMALL_SEA_CIVILIZATION_SORTIENT_ULSTER',  'Dogaressa {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_MERCHANT_REPUBLIC_SMALL_SEA_CIVILIZATION_SORTIENT_ULSTER',  'Republic of Ulster'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_MERCHANT_REPUBLIC_SMALL_SEA_CIVILIZATION_SORTIENT_ULSTER',  'Republic of Ulster'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_MERCHANT_REPUBLIC_SMALL_SEA_ADJ_CIVILIZATION_SORTIENT_ULSTER',  '{1_Adjective} Republic'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_MERCHANT_REPUBLIC_SMALL_SEA_ADJ_CIVILIZATION_SORTIENT_ULSTER',  '{1_Adjective} Republic'	),

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_MERCHANT_REPUBLIC_LARGE_LAND_CIVILIZATION_SORTIENT_ULSTER',  'Grand Prince John I'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_MERCHANT_REPUBLIC_LARGE_LAND_CIVILIZATION_SORTIENT_ULSTER',  'Grand Princess {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_MERCHANT_REPUBLIC_LARGE_LAND_CIVILIZATION_SORTIENT_ULSTER',  'Grand Republic of Ulster'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_MERCHANT_REPUBLIC_LARGE_LAND_CIVILIZATION_SORTIENT_ULSTER',  'Grand Republic of Ulster'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_MERCHANT_REPUBLIC_LARGE_LAND_ADJ_CIVILIZATION_SORTIENT_ULSTER',  'Grand Ulster Republic'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_MERCHANT_REPUBLIC_LARGE_LAND_ADJ_CIVILIZATION_SORTIENT_ULSTER',  'Grand Ulster Republic'	),

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_MERCHANT_REPUBLIC_MEDIUM_LAND_CIVILIZATION_SORTIENT_ULSTER',  'Prince John I'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_MERCHANT_REPUBLIC_MEDIUM_LAND_CIVILIZATION_SORTIENT_ULSTER',  'Princess {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_MERCHANT_REPUBLIC_MEDIUM_LAND_CIVILIZATION_SORTIENT_ULSTER',  '{1_Capital} Republic'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_MERCHANT_REPUBLIC_MEDIUM_LAND_CIVILIZATION_SORTIENT_ULSTER',  '{1_Capital} Republic'	),

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_MERCHANT_REPUBLIC_SMALL_LAND_CIVILIZATION_SORTIENT_ULSTER',  'Alderman {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_MERCHANT_REPUBLIC_SMALL_LAND_CIVILIZATION_SORTIENT_ULSTER',  'Alderwoman {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_MERCHANT_REPUBLIC_SMALL_LAND_CIVILIZATION_SORTIENT_ULSTER',  'Ulster Commonwealth'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_MERCHANT_REPUBLIC_SMALL_LAND_CIVILIZATION_SORTIENT_ULSTER',  'Ulster Commonwealth'	),

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_FASCISM_CIVILIZATION_SORTIENT_ULSTER',  'Chancellor {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_FASCISM_CIVILIZATION_SORTIENT_ULSTER',  'Chancellor {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_FASCISM_CIVILIZATION_SORTIENT_ULSTER',  'Ulster Reich'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_FASCISM_CIVILIZATION_SORTIENT_ULSTER',  'Greater Ulster Reich'	),

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_COMMUNISM_CIVILIZATION_SORTIENT_ULSTER',  'Chairman Hume'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_COMMUNISM_CIVILIZATION_SORTIENT_ULSTER',  'Chairman {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_COMMUNISM_CIVILIZATION_SORTIENT_ULSTER',  'Ulster SSR'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_COMMUNISM_CIVILIZATION_SORTIENT_ULSTER',  'Ulster Soviet Socialist Republic'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_COMMUNISM_ADJ_CIVILIZATION_SORTIENT_ULSTER',  'Ulster SSR'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_COMMUNISM_ADJ_CIVILIZATION_SORTIENT_ULSTER',  'Ulster Soviet Socialist Republic'	),

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_DEMOCRACY_CIVILIZATION_SORTIENT_ULSTER',  'First Minister {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_DEMOCRACY_CIVILIZATION_SORTIENT_ULSTER',  'First Minister {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_DEMOCRACY_CIVILIZATION_SORTIENT_ULSTER',  'N. Ireland'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_DEMOCRACY_CIVILIZATION_SORTIENT_ULSTER',  'Northern Ireland'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_DEMOCRACY_ADJ_CIVILIZATION_SORTIENT_ULSTER',  'N. Irish'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_DEMOCRACY_ADJ_CIVILIZATION_SORTIENT_ULSTER',  'Northern Irish'	),

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_DIGITAL_DEMOCRACY_CIVILIZATION_SORTIENT_ULSTER',  '@humefoundation'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_DIGITAL_DEMOCRACY_CIVILIZATION_SORTIENT_ULSTER',  '@{1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_DIGITAL_DEMOCRACY_CIVILIZATION_SORTIENT_ULSTER',  'Digital Republic of Ulster'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_DIGITAL_DEMOCRACY_CIVILIZATION_SORTIENT_ULSTER',  'Digital Republic of Ulster'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_DIGITAL_DEMOCRACY_ADJ_CIVILIZATION_SORTIENT_ULSTER',  'Digital Ulster Republic'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_DIGITAL_DEMOCRACY_ADJ_CIVILIZATION_SORTIENT_ULSTER',  'Digital Ulster Republic'	),

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_CORPORATE_LIBERTARIANISM_CIVILIZATION_SORTIENT_ULSTER',  'Director {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_CORPORATE_LIBERTARIANISM_CIVILIZATION_SORTIENT_ULSTER',  'Director {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_CORPORATE_LIBERTARIANISM_CIVILIZATION_SORTIENT_ULSTER',  '{1_Name} Incorporated'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_CORPORATE_LIBERTARIANISM_CIVILIZATION_SORTIENT_ULSTER',  '{1_Name} Incorporated'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_CORPORATE_LIBERTARIANISM_ADJ_CIVILIZATION_SORTIENT_ULSTER',  '{1_Adjective} Corporation'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_CORPORATE_LIBERTARIANISM_ADJ_CIVILIZATION_SORTIENT_ULSTER',  '{1_Adjective} Corporation'	);

INSERT INTO LocalizedText (Tag, Text, Language)
SELECT REPLACE(Tag, 'CIVILIZATION_ENGLAND', 'CIVILIZATION_SORTIENT_ULSTER'), Text, Language
FROM LocalizedText
WHERE Tag LIKE '_XSCX_CIVILIZATION_ENGLAND';
/*
INSERT OR REPLACE INTO	 SC_CityLOCRenameDatabase
		(BaseCityTag,				LOCName)
VALUES 	('LOC_ROSETTA_BELFAST','LOC_CITY_NAME_SORTIENT_ULSTER_1'),
		('LOC_ROSETTA_DERRY','LOC_CITY_NAME_SORTIENT_ULSTER_2'),
		('LOC_ROSETTA_LISBURN', 'LOC_CITY_NAME_SORTIENT_ULSTER_3'),
		('LOC_ROSETTA_NEWTOWNARDS','LOC_CITY_NAME_SORTIENT_ULSTER_4'),
		('LOC_ROSETTA_COLERAINE','LOC_CITY_NAME_SORTIENT_ULSTER_5'),
		('LOC_ROSETTA_BANGOR','LOC_CITY_NAME_SORTIENT_ULSTER_6');

INSERT OR REPLACE INTO SC_Base_Name_Inheritance
		(CivOrLeaderType,					Backup1)
VALUES	('CIVILIZATION_SORTIENT_ULSTER',	'CIVILIZATION_ENGLAND'),

/*

	------------------------------------------------------
	------- CHIEFDOM
	------------------------------------------------------

	('en_US'	'LOC_LEADER_MALE_GOVERNMENT_CHIEFDOM_LARGE_CIVILIZATION_SORTIENT_ULSTER',  'High Chief {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_CHIEFDOM_LARGE_CIVILIZATION_SORTIENT_ULSTER',  'High Chieftess {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_CHIEFDOM_LARGE_CIVILIZATION_SORTIENT_ULSTER',  'Ulaid Civilization'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_CHIEFDOM_LARGE_CIVILIZATION_SORTIENT_ULSTER',  'Ulaid Civilization'	),

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_CHIEFDOM_SMALL_CIVILIZATION_SORTIENT_ULSTER',  'Chief {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_CHIEFDOM_SMALL_CIVILIZATION_SORTIENT_ULSTER',  'Chieftess {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_CHIEFDOM_SMALL_CIVILIZATION_SORTIENT_ULSTER',  'Ulaid Chiefdom'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_CHIEFDOM_SMALL_CIVILIZATION_SORTIENT_ULSTER',  'Ulaid Chiefdom'	),

	------------------------------------------------------
	------- JFD NOMADS/0 CITIES
	------------------------------------------------------

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_JFD_NOMADS_CIVILIZATION_SORTIENT_ULSTER',  'Elder {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_JFD_NOMADS_CIVILIZATION_SORTIENT_ULSTER',  'Matriarch {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_JFD_NOMADS_CIVILIZATION_SORTIENT_ULSTER',  'Ulaid Tribes'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_JFD_NOMADS_CIVILIZATION_SORTIENT_ULSTER',  'Ulaid Tribes'	),

	------------------------------------------------------
	------- AUTOCRACY
	------------------------------------------------------

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_AUTOCRACY_CIVILIZATION_SORTIENT_ULSTER',  '{1_Name}, Emperor of Ulster'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_AUTOCRACY_CIVILIZATION_SORTIENT_ULSTER',  '{1_Name}, Empress of Ulster'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_AUTOCRACY_CIVILIZATION_SORTIENT_ULSTER',  'Empire of Ulster'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_AUTOCRACY_CIVILIZATION_SORTIENT_ULSTER',  'Ulster Empire'	),

	------------------------------------------------------
	------- CLASSICAL REPUBLIC
	------------------------------------------------------

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_CLASSICAL_REPUBLIC_CIVILIZATION_SORTIENT_ULSTER',  'Consul {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_CLASSICAL_REPUBLIC_CIVILIZATION_SORTIENT_ULSTER',  'Consul {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_CLASSICAL_REPUBLIC_CIVILIZATION_SORTIENT_ULSTER',  'Republic of Ulster'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_CLASSICAL_REPUBLIC_CIVILIZATION_SORTIENT_ULSTER',  'Republic of Ulster'	),

	------------------------------------------------------
	------- OLIGARCHY
	------------------------------------------------------

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_OLIGARCHY_CIVILIZATION_SORTIENT_ULSTER',  'Hegemon {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_OLIGARCHY_CIVILIZATION_SORTIENT_ULSTER',  'Hegemon {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_OLIGARCHY_CIVILIZATION_SORTIENT_ULSTER',  'Council of Stormont'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_OLIGARCHY_CIVILIZATION_SORTIENT_ULSTER',  'Council of Stormont'	),

	------------------------------------------------------
	------- MERCHANT REPUBLIC
	------------------------------------------------------

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_MERCHANT_REPUBLIC_TINY_CIVILIZATION_SORTIENT_ULSTER',  'Mayor {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_MERCHANT_REPUBLIC_TINY_CIVILIZATION_SORTIENT_ULSTER',  'Mayor {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_MERCHANT_REPUBLIC_TINY_CIVILIZATION_SORTIENT_ULSTER',  'Republic of {1_Capital}'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_MERCHANT_REPUBLIC_TINY_CIVILIZATION_SORTIENT_ULSTER',  'Republic of {1_Capital}'	),

	------- LAND-BASED

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_MERCHANT_REPUBLIC_SMALL_LAND_CIVILIZATION_SORTIENT_ULSTER',  'Count {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_MERCHANT_REPUBLIC_SMALL_LAND_CIVILIZATION_SORTIENT_ULSTER',  'Countess {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_MERCHANT_REPUBLIC_SMALL_LAND_CIVILIZATION_SORTIENT_ULSTER',  'Ulster Commonwealth'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_MERCHANT_REPUBLIC_SMALL_LAND_CIVILIZATION_SORTIENT_ULSTER',  'Ulster Commonwealth'	),

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_MERCHANT_REPUBLIC_MEDIUM_LAND_CIVILIZATION_SORTIENT_ULSTER',  'Chancellor {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_MERCHANT_REPUBLIC_MEDIUM_LAND_CIVILIZATION_SORTIENT_ULSTER',  'Chancellor {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_MERCHANT_REPUBLIC_MEDIUM_LAND_CIVILIZATION_SORTIENT_ULSTER',  'Republic of Ulster'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_MERCHANT_REPUBLIC_MEDIUM_LAND_CIVILIZATION_SORTIENT_ULSTER',  'Republic of Ulster'	),

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_MERCHANT_REPUBLIC_LARGE_LAND_CIVILIZATION_SORTIENT_ULSTER',  'Grand Chancellor {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_MERCHANT_REPUBLIC_LARGE_LAND_CIVILIZATION_SORTIENT_ULSTER',  'Grand Chancellor {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_MERCHANT_REPUBLIC_LARGE_LAND_CIVILIZATION_SORTIENT_ULSTER',  'Grand Republic of Ulster'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_MERCHANT_REPUBLIC_LARGE_LAND_CIVILIZATION_SORTIENT_ULSTER',  'Grand Republic of Ulster'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_MERCHANT_REPUBLIC_LARGE_LAND_ADJ_CIVILIZATION_SORTIENT_ULSTER',  'Grand Ulster Republic'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_MERCHANT_REPUBLIC_LARGE_LAND_ADJ_CIVILIZATION_SORTIENT_ULSTER',  'Grand Ulster Republic'	),

	------------------------------------------------------
	------- MONARCHY
	------------------------------------------------------

	------- GENERIC

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_MONARCHY_TINY_CIVILIZATION_SORTIENT_ULSTER',  'Lord {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_MONARCHY_TINY_CIVILIZATION_SORTIENT_ULSTER',  'Lady {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_MONARCHY_TINY_CIVILIZATION_SORTIENT_ULSTER',  '{1_Capital} Lordship'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_MONARCHY_TINY_CIVILIZATION_SORTIENT_ULSTER',  '{1_Capital} Lordship'	),

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_MONARCHY_SMALL_CIVILIZATION_SORTIENT_ULSTER',  'Earl {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_MONARCHY_SMALL_CIVILIZATION_SORTIENT_ULSTER',  'Countess {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_MONARCHY_SMALL_CIVILIZATION_SORTIENT_ULSTER',  'Earldom of Ulster'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_MONARCHY_SMALL_CIVILIZATION_SORTIENT_ULSTER',  'Earldom of Ulster'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_MONARCHY_SMALL_ADJ_CIVILIZATION_SORTIENT_ULSTER',  'Ulster Earldom'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_MONARCHY_SMALL_ADJ_CIVILIZATION_SORTIENT_ULSTER',  'Ulster Earldom'	),

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_MONARCHY_MEDIUM_CIVILIZATION_SORTIENT_ULSTER',  'King {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_MONARCHY_MEDIUM_CIVILIZATION_SORTIENT_ULSTER',  'Queen {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_MONARCHY_MEDIUM_CIVILIZATION_SORTIENT_ULSTER',  'Kingdom of Ulster'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_MONARCHY_MEDIUM_CIVILIZATION_SORTIENT_ULSTER',  'Kingdom of Ulster'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_MONARCHY_MEDIUM_ADJ_CIVILIZATION_SORTIENT_ULSTER',  'Ulster Kingdom'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_MONARCHY_MEDIUM_ADJ_CIVILIZATION_SORTIENT_ULSTER',  'Ulster Kingdom'	),

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_MONARCHY_LARGE_CIVILIZATION_SORTIENT_ULSTER',  'High King {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_MONARCHY_LARGE_CIVILIZATION_SORTIENT_ULSTER',  'High Queen {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_MONARCHY_LARGE_CIVILIZATION_SORTIENT_ULSTER',  'High Kingdom of Ulster'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_MONARCHY_LARGE_CIVILIZATION_SORTIENT_ULSTER',  'High Kingdom of Ulster'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_MONARCHY_LARGE_ADJ_CIVILIZATION_SORTIENT_ULSTER',  'Ulster High Kingdom'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_MONARCHY_LARGE_ADJ_CIVILIZATION_SORTIENT_ULSTER',  'Ulster High Kingdom'	),


	------------------------------------------------------
	------- COMMUNISM
	------------------------------------------------------

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_COMMUNISM_CIVILIZATION_SORTIENT_ULSTER',  'Chairman {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_COMMUNISM_CIVILIZATION_SORTIENT_ULSTER',  'Chairman {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_COMMUNISM_CIVILIZATION_SORTIENT_ULSTER',  'Soviet Republic of Ulster'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_COMMUNISM_CIVILIZATION_SORTIENT_ULSTER',  'Soviet Republic of Ulster'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_COMMUNISM_ADJ_CIVILIZATION_SORTIENT_ULSTER',  'Ulster Soviet Socialist Republic'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_COMMUNISM_ADJ_CIVILIZATION_SORTIENT_ULSTER',  'Ulster Soviet Socialist Republic'	),

	------------------------------------------------------
	------- DEMOCRACY
	------------------------------------------------------

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_DEMOCRACY_CIVILIZATION_SORTIENT_ULSTER',  'First Minister {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_DEMOCRACY_CIVILIZATION_SORTIENT_ULSTER',  'First Minister {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_DEMOCRACY_CIVILIZATION_SORTIENT_ULSTER',  '{1_Name}'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_DEMOCRACY_CIVILIZATION_SORTIENT_ULSTER',  '{1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_DEMOCRACY_ADJ_CIVILIZATION_SORTIENT_ULSTER',  '{1_Name}'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_DEMOCRACY_ADJ_CIVILIZATION_SORTIENT_ULSTER',  '{1_Name}'	),

	
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_DEMOCRACY_CIVILIZATION_SORTIENT_ULSTER',  'First Minister {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_DEMOCRACY_CIVILIZATION_SORTIENT_ULSTER',  'Republic of {1_Name}'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_DEMOCRACY_CIVILIZATION_SORTIENT_ULSTER',  'Republic of {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_DEMOCRACY_ADJ_CIVILIZATION_SORTIENT_ULSTER',  '{1_Adjective} Republic'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_DEMOCRACY_ADJ_CIVILIZATION_SORTIENT_ULSTER',  '{1_Adjective} Republic'	),

	------------------------------------------------------
	------- FASCISM
	------------------------------------------------------

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_FASCISM_CIVILIZATION_SORTIENT_ULSTER',  'General {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_FASCISM_CIVILIZATION_SORTIENT_ULSTER',  'General {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_FASCISM_CIVILIZATION_SORTIENT_ULSTER',  'Fascist Ulster State'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_FASCISM_CIVILIZATION_SORTIENT_ULSTER',  'Ulster State'	),

	------------------------------------------------------
	------- CORPORATE LIBERTARIANISM
	------------------------------------------------------

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_CORPORATE_LIBERTARIANISM_CIVILIZATION_SORTIENT_ULSTER',  'Director {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_CORPORATE_LIBERTARIANISM_CIVILIZATION_SORTIENT_ULSTER',  'Director {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_CORPORATE_LIBERTARIANISM_CIVILIZATION_SORTIENT_ULSTER',  'Stormont Ltd.'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_CORPORATE_LIBERTARIANISM_CIVILIZATION_SORTIENT_ULSTER',  'Stormont Ltd.'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_CORPORATE_LIBERTARIANISM_ADJ_CIVILIZATION_SORTIENT_ULSTER',  'Stormont Ltd.'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_CORPORATE_LIBERTARIANISM_ADJ_CIVILIZATION_SORTIENT_ULSTER',  'Stormont Ltd.'	),

	------------------------------------------------------
	------- DIGITAL DEMOCRACY
	------------------------------------------------------

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_DIGITAL_DEMOCRACY_CIVILIZATION_SORTIENT_ULSTER',  '@realJohnHume'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_DIGITAL_DEMOCRACY_CIVILIZATION_SORTIENT_ULSTER',  '@{1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_DIGITAL_DEMOCRACY_CIVILIZATION_SORTIENT_ULSTER',  '{1_Name}'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_DIGITAL_DEMOCRACY_CIVILIZATION_SORTIENT_ULSTER',  '{1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_DIGITAL_DEMOCRACY_ADJ_CIVILIZATION_SORTIENT_ULSTER',  'Digital {1_Adjective} Republic'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_DIGITAL_DEMOCRACY_ADJ_CIVILIZATION_SORTIENT_ULSTER',  'Digital {1_Adjective} Republic'	),

	------------------------------------------------------
	------- SYNTHETIC TECHNOCRACY
	------------------------------------------------------

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_SYNTHETIC_TECHNOCRACY_CIVILIZATION_SORTIENT_ULSTER',  'Technocrat {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_SYNTHETIC_TECHNOCRACY_CIVILIZATION_SORTIENT_ULSTER',  'Technocrat {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_SYNTHETIC_TECHNOCRACY_CIVILIZATION_SORTIENT_ULSTER',  '{1_Adjective} Technocracy'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_SYNTHETIC_TECHNOCRACY_CIVILIZATION_SORTIENT_ULSTER',  '{1_Adjective} Technocracy'	),

	------------------------------------------------------
	------- GENERIC EMPIRE
	------------------------------------------------------

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_EMPIRE_CIVILIZATION_SORTIENT_ULSTER',  'Emperor {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_EMPIRE_CIVILIZATION_SORTIENT_ULSTER',  'Empress {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_EMPIRE_CIVILIZATION_SORTIENT_ULSTER',  'Empire of Ulster'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_EMPIRE_CIVILIZATION_SORTIENT_ULSTER',  'Empire of Ulster'	);

	------------------------------------------------------
	------- SCOTLAND
	------------------------------------------------------

	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_CHIEFDOM_LARGE_CIVILIZATION_SCOTLAND',  'Pictish Civilization'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_CHIEFDOM_LARGE_CIVILIZATION_SCOTLAND',  'Pictish Civilization'	),

	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_CHIEFDOM_SMALL_CIVILIZATION_SCOTLAND',  'Pictish Chiefdom'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_CHIEFDOM_SMALL_CIVILIZATION_SCOTLAND',  'Pictish Chiefdom'	),

	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_JFD_HORDE_CIVILIZATION_SCOTLAND',  'Pictish Horde'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_JFD_HORDE_CIVILIZATION_SCOTLAND',  'Pictish Horde'	),

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_AUTOCRACY_CIVILIZATION_SCOTLAND',  'King {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_AUTOCRACY_CIVILIZATION_SCOTLAND',  'Queen {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_AUTOCRACY_CIVILIZATION_SCOTLAND',  'Kingdom of Alba'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_AUTOCRACY_CIVILIZATION_SCOTLAND',  'Kingdom of Alba'	),

	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_CLASSICAL_REPUBLIC_CIVILIZATION_SCOTLAND',  'Republic of Alba'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_CLASSICAL_REPUBLIC_CIVILIZATION_SCOTLAND',  'Republic of Alba'	),

	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_OLIGARCHY_CIVILIZATION_SCOTLAND',  'Kingdom of Alba'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_OLIGARCHY_CIVILIZATION_SCOTLAND',  'Kingdom of Alba'	),

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_MERCHANT_REPUBLIC_TINY_CIVILIZATION_SCOTLAND',  'Lord Provost {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_MERCHANT_REPUBLIC_TINY_CIVILIZATION_SCOTLAND',  'Lady Provostess {1_Name}'	),

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_MONARCHY_TINY_CIVILIZATION_SCOTLAND',  'Thane {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_MONARCHY_TINY_CIVILIZATION_SCOTLAND',  'Lady {1_Name}'	),

	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_MONARCHY_MEDIUM_CIVILIZATION_SCOTLAND',  '{1_Name}, Queen of Scots'	),

	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_MONARCHY_LARGE_CIVILIZATION_SCOTLAND',  '{1_Name}, Queen of Scots'	),

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_MONARCHY_CHRISTIAN_TINY_CIVILIZATION_SCOTLAND',  'Thane {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_MONARCHY_CHRISTIAN_TINY_CIVILIZATION_SCOTLAND',  'Lady {1_Name}'	),

	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_MONARCHY_CHRISTIAN_LARGE_CIVILIZATION_SCOTLAND',  '{1_Name}, Queen of Scots'	),

	('en_US',	'LOC_LEADER_MALE_GOVERNMENT_DEMOCRACY_CIVILIZATION_SCOTLAND',  'First Minister {1_Name}'	),
	('en_US',	'LOC_LEADER_FEMALE_GOVERNMENT_DEMOCRACY_CIVILIZATION_SCOTLAND',  'First Minister {1_Name}'	),
	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_DEMOCRACY_CIVILIZATION_SCOTLAND',  '{1_Name}'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_DEMOCRACY_CIVILIZATION_SCOTLAND',  '{1_Name}'	),

	('en_US',	'LOC_SHORT_CIV_GOVERNMENT_FASCISM_CIVILIZATION_SCOTLAND',  'Caledonia'	),
	('en_US',	'LOC_LONG_CIV_GOVERNMENT_FASCISM_CIVILIZATION_SCOTLAND',  'Caledonia'	), */