INSERT INTO	Types
			(Type,					Kind			)
VALUES		('LEADER_SORTIENT_JOHN_HUME',	'KIND_LEADER'	);

INSERT INTO	Leaders
			(LeaderType,			Name,							InheritFrom,		SceneLayers		)
VALUES		('LEADER_SORTIENT_JOHN_HUME',	'LOC_LEADER_SORTIENT_JOHN_HUME_NAME',	'LEADER_DEFAULT', 	4				);


INSERT INTO	CivilizationLeaders
			(CivilizationType,				LeaderType,				CapitalName					)
VALUES		('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_JOHN_HUME',	'LOC_ROSETTA_BELFAST'	);
		

INSERT INTO	LeaderQuotes
			(LeaderType,			Quote										)
VALUES		('LEADER_SORTIENT_JOHN_HUME',	'LOC_PEDIA_LEADERS_PAGE_SORTIENT_JOHN_HUME_QUOTE'	);

/*
INSERT INTO	CityNames
			(CivilizationType,				LeaderType,				SortIndex,	CityName						)
VALUES		('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_JOHN_HUME',	-1,			'LOC_CITY_NAME_SORTIENT_ULSTER_1'		),
			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_JOHN_HUME',	-1,			'LOC_CITY_NAME_SORTIENT_ULSTER_2'		),
			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_JOHN_HUME',	-1,			'LOC_CITY_NAME_SORTIENT_ULSTER_3'		),
			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_JOHN_HUME',	-1,			'LOC_CITY_NAME_SORTIENT_ULSTER_4'		),
			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_JOHN_HUME',	-1,			'LOC_CITY_NAME_SORTIENT_ULSTER_5'		),
			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_JOHN_HUME',	-1,			'LOC_CITY_NAME_SORTIENT_ULSTER_6'		),
			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_JOHN_HUME',	-1,			'LOC_CITY_NAME_SORTIENT_ULSTER_7'		),
			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_JOHN_HUME',	-1,			'LOC_CITY_NAME_SORTIENT_ULSTER_8'		),
			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_JOHN_HUME',	-1,			'LOC_CITY_NAME_SORTIENT_ULSTER_9'		),
			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_JOHN_HUME',	-1,			'LOC_CITY_NAME_SORTIENT_ULSTER_10'		),
			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_JOHN_HUME',	-1,			'LOC_CITY_NAME_SORTIENT_ULSTER_11'		),
			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_JOHN_HUME',	-1,			'LOC_CITY_NAME_SORTIENT_ULSTER_12'		),
			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_JOHN_HUME',	-1,			'LOC_CITY_NAME_SORTIENT_ULSTER_13'		),
			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_JOHN_HUME',	-1,			'LOC_CITY_NAME_SORTIENT_ULSTER_14'		),
			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_JOHN_HUME',	-1,			'LOC_CITY_NAME_SORTIENT_ULSTER_15'		);
--			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_JOHN_HUME',	-1,			'LOC_CITY_NAME_SORTIENT_ULSTER_17'		),*/
--			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_JOHN_HUME',	-1,			'LOC_CITY_NAME_SORTIENT_ULSTER_18'		),
--			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_JOHN_HUME',	-1,			'LOC_CITY_NAME_SORTIENT_ULSTER_19'		),
--			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_JOHN_HUME',	-1,			'LOC_CITY_NAME_SORTIENT_ULSTER_20'		),
--			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_JOHN_HUME',	-1,			'LOC_CITY_NAME_SORTIENT_ULSTER_21'		),
--			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_JOHN_HUME',	-1,			'LOC_CITY_NAME_SORTIENT_ULSTER_22'		),
--			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_JOHN_HUME',	-1,			'LOC_CITY_NAME_SORTIENT_ULSTER_23'		),
--			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_JOHN_HUME',	-1,			'LOC_CITY_NAME_SORTIENT_ULSTER_24'		),
--			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_JOHN_HUME',	-1,			'LOC_CITY_NAME_SORTIENT_ULSTER_25'		);

