/*
INSERT INTO	Types
		(Type,													Kind			)
VALUES	('TRAIT_LEADER_SORTIENT_FLIGHT_OF_THE_EARLS',			'KIND_TRAIT'	);;
*/

INSERT INTO	Traits
		(TraitType,										Name,															Description												)
VALUES	('TRAIT_LEADER_SORTIENT_FLIGHT_OF_THE_EARLS',	'LOC_TRAIT_LEADER_SORTIENT_FLIGHT_OF_THE_EARLS_NAME',	'LOC_TRAIT_LEADER_SORTIENT_FLIGHT_OF_THE_EARLS_DESCRIPTION'	);
		

INSERT INTO	LeaderTraits
		(LeaderType,			TraitType								)
VALUES	('LEADER_SORTIENT_HUGH_ONEILL',	'TRAIT_LEADER_SORTIENT_FLIGHT_OF_THE_EARLS'	);

INSERT INTO	Types
		(Type,												Kind			)
VALUES	('TRAIT_LEADER_SORTIENT_FLIGHT_OF_THE_EARLS',			'KIND_TRAIT'	);

INSERT INTO TraitModifiers 
		(TraitType,										ModifierId											)
VALUES	('TRAIT_LEADER_SORTIENT_FLIGHT_OF_THE_EARLS',	'ROOSEVELT_COMBAT_BONUS_HOME_CONTINENT'	),
		('TRAIT_LEADER_SORTIENT_FLIGHT_OF_THE_EARLS',	'TRAIT_FLIGHT_OF_THE_EARLS_TECH_TRIGGER'	),
		('TRAIT_LEADER_SORTIENT_FLIGHT_OF_THE_EARLS',	'TRAIT_FLIGHT_OF_THE_EARLS_PRODUCTION'	);

INSERT INTO Modifiers 
    (ModifierId, ModifierType, SubjectRequirementSetId)
VALUES
    ('TRAIT_FLIGHT_OF_THE_EARLS_TECH_TRIGGER', 'MODIFIER_PLAYER_GRANT_RANDOM_TECHNOLOGY', 'FLIGHT_OF_THE_EARLS_DECLARED_JOINT_WAR'),
	('TRAIT_FLIGHT_OF_THE_EARLS_PRODUCTION', 'MODIFIER_PLAYER_ADD_DIPLOMATIC_YIELD_MODIFIER', null);

INSERT INTO ModifierArguments 
    (ModifierId, Name, Type, Value)
VALUES
	('TRAIT_FLIGHT_OF_THE_EARLS_PRODUCTION', 'DiplomaticYieldSource', 'ARGTYPE_IDENTITY', 'JOINT_WAR_INITIATED'),
	('TRAIT_FLIGHT_OF_THE_EARLS_PRODUCTION', 'TurnsActive', 'ARGTYPE_IDENTITY', '10'),
    ('TRAIT_FLIGHT_OF_THE_EARLS_PRODUCTION', 'YieldType', 'ARGTYPE_IDENTITY', 'YIELD_PRODUCTION'),
	('TRAIT_FLIGHT_OF_THE_EARLS_PRODUCTION', 'Amount', 'ARGTYPE_IDENTITY', 50);

INSERT INTO RequirementSets
    (RequirementSetId, RequirementSetType)
VALUES
    ('FLIGHT_OF_THE_EARLS_DECLARED_JOINT_WAR', 'REQUIREMENTSET_TEST_ALL'); 

INSERT INTO RequirementSetRequirements
    (RequirementSetId, RequirementId)
VALUES
    ('FLIGHT_OF_THE_EARLS_DECLARED_JOINT_WAR', 'REQUIRES_PLAYER_DECLARED_JOINT_WAR'); 


