INSERT INTO	Types
			(Type,					Kind			)
VALUES		('LEADER_SORTIENT_HUGH_ONEILL',	'KIND_LEADER'	);

INSERT INTO	Leaders
			(LeaderType,			Name,							InheritFrom,		SceneLayers		)
VALUES		('LEADER_SORTIENT_HUGH_ONEILL',	'LOC_LEADER_SORTIENT_HUGH_ONEILL_NAME',	'LEADER_DEFAULT', 	4				);


INSERT INTO	CivilizationLeaders
			(CivilizationType,				LeaderType,				CapitalName					)
VALUES		('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_HUGH_ONEILL',	'LOC_ROSETTA_OMAGH'	);
		

INSERT INTO	LeaderQuotes
			(LeaderType,			Quote										)
VALUES		('LEADER_SORTIENT_HUGH_ONEILL',	'LOC_PEDIA_LEADERS_PAGE_SORTIENT_HUGH_ONEILL_QUOTE'	);


INSERT INTO	CityNames
			(CivilizationType,				LeaderType,				SortIndex,	CityName						)
VALUES		('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_HUGH_ONEILL',	-1,			'LOC_ROSETTA_BELFAST'		),
			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_HUGH_ONEILL',	-1,			'LOC_ROSETTA_DERRY'		),
			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_HUGH_ONEILL',	-1,			'LOC_ROSETTA_LISBURN'		),
			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_HUGH_ONEILL',	-1,			'LOC_ROSETTA_NEWTOWNARDS'		),
			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_HUGH_ONEILL',	-1,			'LOC_ROSETTA_COLERAINE'		),
			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_HUGH_ONEILL',	-1,			'LOC_ROSETTA_BANGOR'		),
			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_HUGH_ONEILL',	-1,			'LOC_ROSETTA_CAVAN'		),
			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_HUGH_ONEILL',	-1,			'LOC_ROSETTA_DONEGAL'		),
			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_HUGH_ONEILL',	-1,			'LOC_ROSETTA_ARMAGH'		),
			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_HUGH_ONEILL',	-1,			'LOC_ROSETTA_NEWRY'		),
			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_HUGH_ONEILL',	-1,			'LOC_ROSETTA_BALLYMENA'		),
			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_HUGH_ONEILL',	-1,			'LOC_ROSETTA_CARRICKFERGUS'		),
			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_HUGH_ONEILL',	-1,			'LOC_ROSETTA_ANTRIM'		),
			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_HUGH_ONEILL',	-1,			'LOC_ROSETTA_OMAGH'		),
			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_HUGH_ONEILL',	-1,			'LOC_ROSETTA_ENNISKILLEN'		),
			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_HUGH_ONEILL',	-1,			'LOC_ROSETTA_DOWNPATRICK'		),
			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_HUGH_ONEILL',	-1,			'LOC_ROSETTA_LARNE'		),
  			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_HUGH_ONEILL',	-1,			'LOC_ROSETTA_LIMAVADY'		),
  			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_HUGH_ONEILL',	-1,			'LOC_ROSETTA_BANBRIDGE'		),
  			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_HUGH_ONEILL',	-1,			'LOC_ROSETTA_PORTADOWN'		),
  			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_HUGH_ONEILL',	-1,			'LOC_ROSETTA_DUNGANNON'		),
  			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_HUGH_ONEILL',	-1,			'LOC_ROSETTA_COOKSTOWN'		),
  			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_HUGH_ONEILL',	-1,			'LOC_ROSETTA_COMBER'		),
  			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_HUGH_ONEILL',	-1,			'LOC_ROSETTA_BALLYMONEY'		),
  			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_HUGH_ONEILL',	-1,			'LOC_ROSETTA_MAGHERAFELT'		),
  			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_HUGH_ONEILL',	-1,			'LOC_ROSETTA_NEWCASTLE'		),
			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_HUGH_ONEILL',	-1,			'LOC_ROSETTA_EGLINTON'		),
			('CIVILIZATION_SORTIENT_ULSTER',		'LEADER_SORTIENT_HUGH_ONEILL',	-1,			'LOC_ROSETTA_CARRYDUFF'		);